/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppManagerRouteImport } from './routes/_app.manager'
import { Route as AppEmployeeRouteImport } from './routes/_app.employee'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppManagerTeamRouteImport } from './routes/_app.manager.team'
import { Route as AppManagerSharedRouteImport } from './routes/_app.manager.shared'
import { Route as AppManagerReportsRouteImport } from './routes/_app.manager.reports'
import { Route as AppManagerPerformanceRouteImport } from './routes/_app.manager.performance'
import { Route as AppManagerApprovalsRouteImport } from './routes/_app.manager.approvals'
import { Route as AppManagerAnalyticsRouteImport } from './routes/_app.manager.analytics'
import { Route as AppManagerActivityRouteImport } from './routes/_app.manager.activity'
import { Route as AppEmployeeInsightsRouteImport } from './routes/_app.employee.insights'
import { Route as AppEmployeeGoalsRouteImport } from './routes/_app.employee.goals'
import { Route as AppEmployeeGoalDetailsRouteImport } from './routes/_app.employee.goal-details'
import { Route as AppEmployeeCreateGoalRouteImport } from './routes/_app.employee.create-goal'
import { Route as AppEmployeeCheckinsRouteImport } from './routes/_app.employee.checkins'
import { Route as AppEmployeeCalendarRouteImport } from './routes/_app.employee.calendar'
import { Route as AppEmployeeAiRouteImport } from './routes/_app.employee.ai'
import { Route as AppEmployeeActivityRouteImport } from './routes/_app.employee.activity'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminSecurityRouteImport } from './routes/_app.admin.security'
import { Route as AppAdminReportsRouteImport } from './routes/_app.admin.reports'
import { Route as AppAdminEscalationsRouteImport } from './routes/_app.admin.escalations'
import { Route as AppAdminComplianceRouteImport } from './routes/_app.admin.compliance'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app.admin.analytics'
import { Route as AppAdminActivityRouteImport } from './routes/_app.admin.activity'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerRoute = AppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeRoute = AppEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerTeamRoute = AppManagerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerSharedRoute = AppManagerSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerReportsRoute = AppManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerPerformanceRoute = AppManagerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerApprovalsRoute = AppManagerApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerAnalyticsRoute = AppManagerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerActivityRoute = AppManagerActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppEmployeeInsightsRoute = AppEmployeeInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppEmployeeRoute,
} as any)
const AppEmployeeGoalsRoute = AppEmployeeGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppEmployeeRoute,
} as any)
const AppEmployeeGoalDetailsRoute = AppEmployeeGoalDetailsRouteImport.update({
  id: '/goal-details',
  path: '/goal-details',
  getParentRoute: () => AppEmployeeRoute,
} as any)
const AppEmployeeCreateGoalRoute = AppEmployeeCreateGoalRouteImport.update({
  id: '/create-goal',
  path: '/create-goal',
  getParentRoute: () => AppEmployeeRoute,
} as any)
const AppEmployeeCheckinsRoute = AppEmployeeCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => AppEmployeeRoute,
} as any)
const AppEmployeeCalendarRoute = AppEmployeeCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppEmployeeRoute,
} as any)
const AppEmployeeAiRoute = AppEmployeeAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppEmployeeRoute,
} as any)
const AppEmployeeActivityRoute = AppEmployeeActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppEmployeeRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSecurityRoute = AppAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEscalationsRoute = AppAdminEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminComplianceRoute = AppAdminComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminActivityRoute = AppAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/ai': typeof AppAiRoute
  '/employee': typeof AppEmployeeRouteWithChildren
  '/manager': typeof AppManagerRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/compliance': typeof AppAdminComplianceRoute
  '/admin/escalations': typeof AppAdminEscalationsRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/security': typeof AppAdminSecurityRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/employee/activity': typeof AppEmployeeActivityRoute
  '/employee/ai': typeof AppEmployeeAiRoute
  '/employee/calendar': typeof AppEmployeeCalendarRoute
  '/employee/checkins': typeof AppEmployeeCheckinsRoute
  '/employee/create-goal': typeof AppEmployeeCreateGoalRoute
  '/employee/goal-details': typeof AppEmployeeGoalDetailsRoute
  '/employee/goals': typeof AppEmployeeGoalsRoute
  '/employee/insights': typeof AppEmployeeInsightsRoute
  '/manager/activity': typeof AppManagerActivityRoute
  '/manager/analytics': typeof AppManagerAnalyticsRoute
  '/manager/approvals': typeof AppManagerApprovalsRoute
  '/manager/performance': typeof AppManagerPerformanceRoute
  '/manager/reports': typeof AppManagerReportsRoute
  '/manager/shared': typeof AppManagerSharedRoute
  '/manager/team': typeof AppManagerTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/ai': typeof AppAiRoute
  '/employee': typeof AppEmployeeRouteWithChildren
  '/manager': typeof AppManagerRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/compliance': typeof AppAdminComplianceRoute
  '/admin/escalations': typeof AppAdminEscalationsRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/security': typeof AppAdminSecurityRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/employee/activity': typeof AppEmployeeActivityRoute
  '/employee/ai': typeof AppEmployeeAiRoute
  '/employee/calendar': typeof AppEmployeeCalendarRoute
  '/employee/checkins': typeof AppEmployeeCheckinsRoute
  '/employee/create-goal': typeof AppEmployeeCreateGoalRoute
  '/employee/goal-details': typeof AppEmployeeGoalDetailsRoute
  '/employee/goals': typeof AppEmployeeGoalsRoute
  '/employee/insights': typeof AppEmployeeInsightsRoute
  '/manager/activity': typeof AppManagerActivityRoute
  '/manager/analytics': typeof AppManagerAnalyticsRoute
  '/manager/approvals': typeof AppManagerApprovalsRoute
  '/manager/performance': typeof AppManagerPerformanceRoute
  '/manager/reports': typeof AppManagerReportsRoute
  '/manager/shared': typeof AppManagerSharedRoute
  '/manager/team': typeof AppManagerTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/ai': typeof AppAiRoute
  '/_app/employee': typeof AppEmployeeRouteWithChildren
  '/_app/manager': typeof AppManagerRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/admin/activity': typeof AppAdminActivityRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/compliance': typeof AppAdminComplianceRoute
  '/_app/admin/escalations': typeof AppAdminEscalationsRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
  '/_app/admin/security': typeof AppAdminSecurityRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/employee/activity': typeof AppEmployeeActivityRoute
  '/_app/employee/ai': typeof AppEmployeeAiRoute
  '/_app/employee/calendar': typeof AppEmployeeCalendarRoute
  '/_app/employee/checkins': typeof AppEmployeeCheckinsRoute
  '/_app/employee/create-goal': typeof AppEmployeeCreateGoalRoute
  '/_app/employee/goal-details': typeof AppEmployeeGoalDetailsRoute
  '/_app/employee/goals': typeof AppEmployeeGoalsRoute
  '/_app/employee/insights': typeof AppEmployeeInsightsRoute
  '/_app/manager/activity': typeof AppManagerActivityRoute
  '/_app/manager/analytics': typeof AppManagerAnalyticsRoute
  '/_app/manager/approvals': typeof AppManagerApprovalsRoute
  '/_app/manager/performance': typeof AppManagerPerformanceRoute
  '/_app/manager/reports': typeof AppManagerReportsRoute
  '/_app/manager/shared': typeof AppManagerSharedRoute
  '/_app/manager/team': typeof AppManagerTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/ai'
    | '/employee'
    | '/manager'
    | '/notifications'
    | '/settings'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/compliance'
    | '/admin/escalations'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/employee/activity'
    | '/employee/ai'
    | '/employee/calendar'
    | '/employee/checkins'
    | '/employee/create-goal'
    | '/employee/goal-details'
    | '/employee/goals'
    | '/employee/insights'
    | '/manager/activity'
    | '/manager/analytics'
    | '/manager/approvals'
    | '/manager/performance'
    | '/manager/reports'
    | '/manager/shared'
    | '/manager/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/ai'
    | '/employee'
    | '/manager'
    | '/notifications'
    | '/settings'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/compliance'
    | '/admin/escalations'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/employee/activity'
    | '/employee/ai'
    | '/employee/calendar'
    | '/employee/checkins'
    | '/employee/create-goal'
    | '/employee/goal-details'
    | '/employee/goals'
    | '/employee/insights'
    | '/manager/activity'
    | '/manager/analytics'
    | '/manager/approvals'
    | '/manager/performance'
    | '/manager/reports'
    | '/manager/shared'
    | '/manager/team'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/ai'
    | '/_app/employee'
    | '/_app/manager'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_app/admin/activity'
    | '/_app/admin/analytics'
    | '/_app/admin/audit'
    | '/_app/admin/compliance'
    | '/_app/admin/escalations'
    | '/_app/admin/reports'
    | '/_app/admin/security'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/employee/activity'
    | '/_app/employee/ai'
    | '/_app/employee/calendar'
    | '/_app/employee/checkins'
    | '/_app/employee/create-goal'
    | '/_app/employee/goal-details'
    | '/_app/employee/goals'
    | '/_app/employee/insights'
    | '/_app/manager/activity'
    | '/_app/manager/analytics'
    | '/_app/manager/approvals'
    | '/_app/manager/performance'
    | '/_app/manager/reports'
    | '/_app/manager/shared'
    | '/_app/manager/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager': {
      id: '/_app/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AppManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee': {
      id: '/_app/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AppEmployeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/team': {
      id: '/_app/manager/team'
      path: '/team'
      fullPath: '/manager/team'
      preLoaderRoute: typeof AppManagerTeamRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/shared': {
      id: '/_app/manager/shared'
      path: '/shared'
      fullPath: '/manager/shared'
      preLoaderRoute: typeof AppManagerSharedRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/reports': {
      id: '/_app/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof AppManagerReportsRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/performance': {
      id: '/_app/manager/performance'
      path: '/performance'
      fullPath: '/manager/performance'
      preLoaderRoute: typeof AppManagerPerformanceRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/approvals': {
      id: '/_app/manager/approvals'
      path: '/approvals'
      fullPath: '/manager/approvals'
      preLoaderRoute: typeof AppManagerApprovalsRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/analytics': {
      id: '/_app/manager/analytics'
      path: '/analytics'
      fullPath: '/manager/analytics'
      preLoaderRoute: typeof AppManagerAnalyticsRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/activity': {
      id: '/_app/manager/activity'
      path: '/activity'
      fullPath: '/manager/activity'
      preLoaderRoute: typeof AppManagerActivityRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/employee/insights': {
      id: '/_app/employee/insights'
      path: '/insights'
      fullPath: '/employee/insights'
      preLoaderRoute: typeof AppEmployeeInsightsRouteImport
      parentRoute: typeof AppEmployeeRoute
    }
    '/_app/employee/goals': {
      id: '/_app/employee/goals'
      path: '/goals'
      fullPath: '/employee/goals'
      preLoaderRoute: typeof AppEmployeeGoalsRouteImport
      parentRoute: typeof AppEmployeeRoute
    }
    '/_app/employee/goal-details': {
      id: '/_app/employee/goal-details'
      path: '/goal-details'
      fullPath: '/employee/goal-details'
      preLoaderRoute: typeof AppEmployeeGoalDetailsRouteImport
      parentRoute: typeof AppEmployeeRoute
    }
    '/_app/employee/create-goal': {
      id: '/_app/employee/create-goal'
      path: '/create-goal'
      fullPath: '/employee/create-goal'
      preLoaderRoute: typeof AppEmployeeCreateGoalRouteImport
      parentRoute: typeof AppEmployeeRoute
    }
    '/_app/employee/checkins': {
      id: '/_app/employee/checkins'
      path: '/checkins'
      fullPath: '/employee/checkins'
      preLoaderRoute: typeof AppEmployeeCheckinsRouteImport
      parentRoute: typeof AppEmployeeRoute
    }
    '/_app/employee/calendar': {
      id: '/_app/employee/calendar'
      path: '/calendar'
      fullPath: '/employee/calendar'
      preLoaderRoute: typeof AppEmployeeCalendarRouteImport
      parentRoute: typeof AppEmployeeRoute
    }
    '/_app/employee/ai': {
      id: '/_app/employee/ai'
      path: '/ai'
      fullPath: '/employee/ai'
      preLoaderRoute: typeof AppEmployeeAiRouteImport
      parentRoute: typeof AppEmployeeRoute
    }
    '/_app/employee/activity': {
      id: '/_app/employee/activity'
      path: '/activity'
      fullPath: '/employee/activity'
      preLoaderRoute: typeof AppEmployeeActivityRouteImport
      parentRoute: typeof AppEmployeeRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/security': {
      id: '/_app/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AppAdminSecurityRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/escalations': {
      id: '/_app/admin/escalations'
      path: '/escalations'
      fullPath: '/admin/escalations'
      preLoaderRoute: typeof AppAdminEscalationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/compliance': {
      id: '/_app/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AppAdminComplianceRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/activity': {
      id: '/_app/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AppAdminActivityRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminActivityRoute: typeof AppAdminActivityRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminComplianceRoute: typeof AppAdminComplianceRoute
  AppAdminEscalationsRoute: typeof AppAdminEscalationsRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminSecurityRoute: typeof AppAdminSecurityRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminActivityRoute: AppAdminActivityRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminComplianceRoute: AppAdminComplianceRoute,
  AppAdminEscalationsRoute: AppAdminEscalationsRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminSecurityRoute: AppAdminSecurityRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppEmployeeRouteChildren {
  AppEmployeeActivityRoute: typeof AppEmployeeActivityRoute
  AppEmployeeAiRoute: typeof AppEmployeeAiRoute
  AppEmployeeCalendarRoute: typeof AppEmployeeCalendarRoute
  AppEmployeeCheckinsRoute: typeof AppEmployeeCheckinsRoute
  AppEmployeeCreateGoalRoute: typeof AppEmployeeCreateGoalRoute
  AppEmployeeGoalDetailsRoute: typeof AppEmployeeGoalDetailsRoute
  AppEmployeeGoalsRoute: typeof AppEmployeeGoalsRoute
  AppEmployeeInsightsRoute: typeof AppEmployeeInsightsRoute
}

const AppEmployeeRouteChildren: AppEmployeeRouteChildren = {
  AppEmployeeActivityRoute: AppEmployeeActivityRoute,
  AppEmployeeAiRoute: AppEmployeeAiRoute,
  AppEmployeeCalendarRoute: AppEmployeeCalendarRoute,
  AppEmployeeCheckinsRoute: AppEmployeeCheckinsRoute,
  AppEmployeeCreateGoalRoute: AppEmployeeCreateGoalRoute,
  AppEmployeeGoalDetailsRoute: AppEmployeeGoalDetailsRoute,
  AppEmployeeGoalsRoute: AppEmployeeGoalsRoute,
  AppEmployeeInsightsRoute: AppEmployeeInsightsRoute,
}

const AppEmployeeRouteWithChildren = AppEmployeeRoute._addFileChildren(
  AppEmployeeRouteChildren,
)

interface AppManagerRouteChildren {
  AppManagerActivityRoute: typeof AppManagerActivityRoute
  AppManagerAnalyticsRoute: typeof AppManagerAnalyticsRoute
  AppManagerApprovalsRoute: typeof AppManagerApprovalsRoute
  AppManagerPerformanceRoute: typeof AppManagerPerformanceRoute
  AppManagerReportsRoute: typeof AppManagerReportsRoute
  AppManagerSharedRoute: typeof AppManagerSharedRoute
  AppManagerTeamRoute: typeof AppManagerTeamRoute
}

const AppManagerRouteChildren: AppManagerRouteChildren = {
  AppManagerActivityRoute: AppManagerActivityRoute,
  AppManagerAnalyticsRoute: AppManagerAnalyticsRoute,
  AppManagerApprovalsRoute: AppManagerApprovalsRoute,
  AppManagerPerformanceRoute: AppManagerPerformanceRoute,
  AppManagerReportsRoute: AppManagerReportsRoute,
  AppManagerSharedRoute: AppManagerSharedRoute,
  AppManagerTeamRoute: AppManagerTeamRoute,
}

const AppManagerRouteWithChildren = AppManagerRoute._addFileChildren(
  AppManagerRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAiRoute: typeof AppAiRoute
  AppEmployeeRoute: typeof AppEmployeeRouteWithChildren
  AppManagerRoute: typeof AppManagerRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAiRoute: AppAiRoute,
  AppEmployeeRoute: AppEmployeeRouteWithChildren,
  AppManagerRoute: AppManagerRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
